version: '3.3'
services:
  application:
    image: metis:0.0.1
    container_name: metis
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/metis_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12-alpine
    container_name: metis-postgres
    environment:
      - POSTGRES_DB=metis_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - metis_psql:/var/lib/postgresql/data
volumes:
  metis_psql:
